language: node_js
node_js:
- '0.12'
- '0.11'
install:
- npm install
- jspm install
script:
- gulp build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: AlXzyhO85ogozp/DsuNpbirNO2cSXgRs8l5xWV3m8KPCo0f4WlrVLJis0npBDFqQ2rL6erT4592dPv1yFdjHO4rS4thb2/hb4AC8a8M8RFca8arrZ6dqe9SwD3EXveVYepxBmI/yfUaKGrcRtscVD15ff9oyNNxT2Lbwr8w3iyl0IpHaLaf1dLcJy3OcEh9EQOgeYGX9KrSP/ZNaVOtt3JckqnftyUfPJqw4Rkf9ZtB2yIesW7BMJ+1q1pTJImlZQ/qQg/EbF219mjIb9eGEne/WbtZVUT7Cwkpj7aBQa6I1fUczXgjJP3aL4Y6rLl6LJO3zIWyF6qDOMP2zbYKnYzaQettZJ+Dxa9S8Zan0yBemjlpfT3cmbb4pnhNlLP0xqkOpfMw0OEIGb63AoV+w785UuMEiOegqut6/rcL69jHQfMuIp64ULQYJfmq/fqzNq+gplNT6UXvPeoJqUQ11kUR5mfN8GSEoPnQuzlhRLJ6CTafT59UFyvHKRem6Oxd/L4wrXdUCMZS9pcsh5K4M7d5NdTVfEPhlhZ9IfBZpD+GZzz74dYnMRg69AdcnH/AV2aT5Y8apLHKKITm36Qa1OYTfmVokgb7pbKwUezMNvq8xi0J8nNmAUifqhu+/QTIz3s3pAl2j9jSA6hvgFE1HCXCrmcGhqAKQC8p94FujJEU=
  app:
    master: angular-2-gravatar-example
  on:
    repo: agconti/angular-2-gravatar-example
notifications:
  email: false
sudo: false
matrix:
  fast_finish: true
